language: bash

os:
- linux
- osx

services:
  - docker

script:
- bash -c 'time bin/bats --tap test/{bats,suite}.bats'
- test -x "$(which docker)" && {
    docker build --tag bats:latest . &&
    docker run -it bats:latest --tap /opt/bats/test/{bats,suite}.bats &&
    bash -c 'time bin/bats --tap test/docker.bats' || return $?;
  } || true

notifications:
  email:
    on_success: never
