- type: application/vnd.org.wtwta.project
  main: bats-bvb
  id: bats-bvb
  version: 1.1.0-bvb1 # bats-bvb
  scripts:
    install:
      - gem install ronn
    init:
      - htd package update
      - htd package remotes-init
      - vc regenerate
    check:
      - git-versioning check
      - test man/bats.1 -nt man/bats.1.ronn
      - test man/bats.7 -nt man/bats.7.ronn
    build:
      - cd man && make
    global-install:
      - ./install.sh /usr/local
    test:
      - ./bin/bats test
    todo.txt:
      - htd tasks --Check-All-Tags --Check-All-Files --update
  pd-meta:
    tasks:
      document: todo.txt
  urls:
    wiki: git@github.com:bats-core/bats-core.wiki.git
    wiki-fork: git@github.com:bvberkum/bats-core.wiki.git
  repositories:
    origin: git@github.com:bvberkum/bats-core.git
    core: https://github.com/bats-core/bats-core.git
    sstephenson: https://github.com/sstephenson/bats.git
    tpraxl: https://github.com/tpraxl/bats-core.git
    tterranigma: https://github.com/tterranigma/bats-core.git
  dist:
    - origin
# git-versioning main: bats-bvb
