- type: application/vnd.org.wtwta.project
  main: bats-bvb
  id: bats-bvb
  version: 1.1.0-bvb1 # bats-bvb
  scripts:
    install:
      - gem install ronn
    init:
      - htd package update
      - htd package remotes-init
      - vc regenerate
    check:
      - git-versioning check
      - test man/bats.1 -nt man/bats.1.ronn
      - test man/bats.7 -nt man/bats.7.ronn
    build:
      - cd man && make
    global-install:
      - ./install.sh /usr/local
    test:
      - ./bin/bats test
  urls:
    wiki: git@github.com:bats-core/bats-core.wiki.git
    wiki-fork: git@github.com:bvberkum/bats-core.wiki.git
  repositories:
    core: git@github.com:bats-core/bats-core.git
    origin: git@github.com:bvberkum/bats-core.git
    sstephenson: https://github.com/sstephenson/bats.git
  dist:
    - origin
# git-versioning main: bats-bvb
