- main: bats-mpe
  id: bats-mpe
  version: 0.4.0-bvb4 # bats-mpe
  scripts:
    install:
      - gem install ronn
    init:
      - htd package update
      - htd package remotes-init
      - vc regenerate
    check:
      - git-versioning check
      - test man/bats.1 -nt man/bats.1.ronn
      - test man/bats.7 -nt man/bats.7.ronn
    build:
      - cd man && make
    global-install:
      - ./install.sh /usr/local
    test:
      - bats test/
  repositories:
    core: git@github.com:bats-core/bats-core.git
    core-fork: git@github.com:bvberkum/bats-core.git
    origin: git@github.com:bvberkum/bats.git
    sstephenson: https://github.com/sstephenson/bats.git
